---
abstract: 'check for POD errors in files'
author:
  - 'Currently maintained by David E. Wheeler, C<< <david@justatheory.com> >>.'
build_requires:
  File::Spec: 0
  Pod::Simple: 3.05
  Test::More: 0.62
configure_requires:
  Module::Build: 0.30
dynamic_config: 1
generated_by: 'Module::Build version 0.3706, CPAN::Meta::Converter version 2.110550'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Pod
provides:
  Test::Pod:
    file: lib/Test/Pod.pm
    version: 1.45
requires:
  File::Spec: 0
  Pod::Simple: 3.05
  Test::Builder::Tester: 1.02
  Test::More: 0.62
resources:
  bugtracker: http://github.com/theory/test-pod/issues/
  homepage: http://search.cpan.org/dist/Test-Pod/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/theory/test-pod/tree/
version: 1.45
